version: '3.8'

services:
  debug:
    container_name: isles22_submission_POBOTRI-debug
    hostname: isles22_submission_POBOTRI-debug
    build:
      context: ${PWD}
      # shm_size: 128m
      dockerfile: Dockerfile-debug
    tty: true
    stdin_open: true
    deploy:
      resources:
        # limits:
          # memory: 15g
          # pids: 256
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
            count: 1
            # device_ids: ['0']
    volumes:
      - ${PWD}:/opt/algorithm
      - ${PWD}/test:/input:ro
      # - ${PWD}/output:/output:rw